In [3]:
# Numpy stands for Numerical Python
# It allows several mathematical operations 
# Faster operations when compared to list

In [4]:
import numpy as np

In [5]:
# List v/s Numpy Time Taken

In [6]:
from time import process_time

In [7]:
l=[i for i in range(10000)]

startime=process_time()

l=[i+5 for i in l]

endtime=process_time()

print(endtime-startime)

0.0


In [8]:
arr=np.array([i for i in range(10000)])
startime=process_time()

arr+=5

endtime=process_time()
print(endtime-startime)

0.0


In [9]:
list1=[1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [10]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

# <class 'numpy.ndarray'> it is equivalent to matrix or we can
# say array of n-dimensions.

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
arr1.shape # (5 col * 1 row)

(5,)

In [12]:
mat=np.array([[1,2,3],
     [4,5,6]])
mat.shape

# shape return row*col but above it tells that it is 1-d numpy array
# and its row column depend on how we reshape it

(2, 3)

In [13]:
mat=np.array([[1,2,3],[4,5,6]],dtype='float')
print(mat)

[[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
# Initial Placeholder in numpy array

In [15]:
# create a numpy array of zeroes

mat=np.zeros((4,3))
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# create a numpy array of ones

mat=np.ones((3,3))
mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# Create a array of particular value
mat=np.full((4,3),10)
mat

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [18]:
# create an identity matrix
# identity matrix is an square matrix 
# 4 is row and col both
mat=np.eye((4))
mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
# create numpy array with random values
mat=np.random.random((4,3))
mat

array([[0.11603124, 0.92845798, 0.86428732],
       [0.48194323, 0.26755523, 0.65778155],
       [0.53162726, 0.59882953, 0.74728316],
       [0.75964092, 0.02731151, 0.87683536]])

In [20]:
# create numpy array with random integers within a range
mat=np.random.randint(10,100,(4,3))
mat

array([[33, 21, 32],
       [31, 67, 27],
       [11, 80, 68],
       [36, 95, 87]])

In [21]:
# Create an array of evenly spaced values

In [25]:
mat=np.linspace(10,30,10) # 10 evenly spaced values b/w 10 and 30
mat

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

In [28]:
# array of evenly spaced values, specifying the STEP
mat=np.arange(10,30,5) # b/w 10 and 30 with a step of 5
mat

array([10, 15, 20, 25])

In [30]:
# convert a list to a numpy array

l=[1,2,3,4,5]

arr=np.asarray(l)
print(type(arr))
arr


<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [31]:
# Analysing a particular array

In [32]:
mat=np.random.randint(10,19,(5,5))
mat

array([[12, 17, 10, 13, 16],
       [10, 13, 16, 15, 16],
       [18, 13, 17, 11, 15],
       [12, 18, 15, 13, 16],
       [10, 12, 10, 14, 11]])

In [33]:
# array dimensions
mat.shape

(5, 5)

In [35]:
# number of dimensions - 1-d, 2-d, 3-d
mat.ndim

2

In [36]:
# no of element in arr
mat.size

25

In [37]:
# chcecking the datatype 
mat.dtype

dtype('int32')

In [38]:
# Mathematical operations on a numpy array

l=[1,2,3,4,5]
m=[6,7,8,9,10]

l+m

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [39]:
arr=np.random.randint(0,10,(3,3))
arr

array([[3, 1, 2],
       [4, 2, 7],
       [8, 1, 1]])

In [40]:
brr=np.random.randint(10,20,(3,3))
brr

array([[15, 18, 17],
       [10, 17, 10],
       [15, 13, 19]])

In [41]:
arr+brr # element wise addition

array([[18, 19, 19],
       [14, 19, 17],
       [23, 14, 20]])

In [42]:
arr-brr # element wise subtraction

array([[-12, -17, -15],
       [ -6, -15,  -3],
       [ -7, -12, -18]])

In [43]:
arr*brr # element wise multiplication

array([[ 45,  18,  34],
       [ 40,  34,  70],
       [120,  13,  19]])

In [44]:
arr/brr # element wise division

array([[0.2       , 0.05555556, 0.11764706],
       [0.4       , 0.11764706, 0.7       ],
       [0.53333333, 0.07692308, 0.05263158]])

In [46]:
# Another way to add
np.add(arr,brr)

array([[18, 19, 19],
       [14, 19, 17],
       [23, 14, 20]])

In [47]:
# Another way to subtract
np.subtract(arr,brr)

array([[-12, -17, -15],
       [ -6, -15,  -3],
       [ -7, -12, -18]])

In [48]:
# Another way to multiply
np.multiply(arr,brr)

array([[ 45,  18,  34],
       [ 40,  34,  70],
       [120,  13,  19]])

In [49]:
# Another way to divide
np.divide(arr,brr)

array([[0.2       , 0.05555556, 0.11764706],
       [0.4       , 0.11764706, 0.7       ],
       [0.53333333, 0.07692308, 0.05263158]])

In [50]:
# Array Manipulation
mat=np.random.randint(0,10,(2,3))
mat

array([[0, 4, 1],
       [6, 7, 5]])

In [51]:
mat.shape

(2, 3)

In [55]:
trans=np.transpose(mat)
trans

array([[0, 6],
       [4, 7],
       [1, 5]])

In [56]:
trans.shape

(3, 2)

In [57]:
# Array Manipulation
mat=np.random.randint(0,10,(2,3))
mat

array([[4, 4, 6],
       [5, 4, 1]])

In [59]:
# another way of transpose
trans=mat.T
trans

array([[4, 5],
       [4, 4],
       [6, 1]])

In [60]:
trans.shape

(3, 2)

In [65]:
# Reshaping the array
mat=np.random.randint(10,20,(2,3))
mat

array([[19, 17, 15],
       [17, 19, 15]])

In [66]:
mat.shape,mat.size

((2, 3), 6)

In [68]:
new=mat.reshape(3,2)
new

array([[19, 17],
       [15, 17],
       [19, 15]])

In [69]:
new.shape

(3, 2)